In [12]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)

Python list addition time: 0.1564316749572754


In [13]:
size = 1_000_000_000_000_000_000_000_000_000_000_000_000000_000_000_000_000_000_000_000_000_000_000_000

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print("NumPy array addition time:", end - start) 

NumPy array addition time: 0.019997596740722656


In [14]:
import sys

list_data = list(range(1000000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8000056000000 bytes
NumPy array size: 8000000 bytes


In [20]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x**2 for x in list1]
end = time.time()
print("Python list addition time:", end - start)

Python list addition time: 0.17004871368408203


In [21]:
import numpy as np
import time

# Python list
size = 1_000_000
array = np.array([range(size)])


start = time.time()
result = array**2
end = time.time()
print("Python list addition time:", end - start)

Python list addition time: 0.02209615707397461


In [22]:

 
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
 
print(arr1)  # [1 2 3 4 5]
print(arr2)  
# [[1 2 3]
#  [4 5 6]]

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [24]:
np.zeros((3, 3))    # 3x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:

np.ones((2, 4))     # 2x4 array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:

np.full((2, 2), 7)  # 2x2 array filled with 7

array([[7, 7],
       [7, 7]])

In [28]:

np.eye(4)           # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:

np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)

array([1, 3, 5, 7, 9])

In [30]:

np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:

arr = (np.random.rand(3, 3) * 100).astype(int)
print(arr)

arr = arr.astype(int)

print(arr)
print("Shape:", arr.shape)

[[80 81 92]
 [68 93 12]
 [18 18 43]]
[[80 81 92]
 [68 93 12]
 [18 18 43]]
Shape: (3, 3)


In [40]:
arr = np.array([1.1, 2.2, 3.3])
int_arr = arr.astype(int)
print(int_arr)

[1 2 3]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6])
even_numbers = arr[arr % 2 == 0]
print(even_numbers)

[2 4 6]


In [43]:
arr = np.arange(1, 10)
reshaped = arr.reshape(3, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
arr = np.array([10, 45, 60, 23, 89, 50, 100])
filtered = arr[arr > 50]
print(filtered)

[ 60  89 100]
